<template>
  <div id="aboutus">
    <div class="header">
      <Header></Header>
    </div>
    <div id="body">
      <div class="container">
        <h1>About DPLibrary</h1>
        <p>The DP-Library is an information platform
          <a href="http://www.bibdr.org/" target="_blank">sponsored by BIBDR (Beijing Institute Of Big Data Research)</a>,
          providing the DP models for various systems generated by different groups. Development of the DP-Library is supported by the
          <a href="http://bbs.deepmd.org/" target="_blank">DeePMD group</a>, .
        </p>
      </div>
    </div>

    <Footer></Footer>
  </div>
</template>

<script>
import Header from "../components/Header";
import Footer from "../components/Footer";
export default {
  name: "AboutUs",
  components:{
    Header,
    Footer
  }
}
</script>

<style scoped>
#body{
  min-height: 900px;
}
.header{
  height: 100px;
  background: url("../assets/images/详情页头图.png");
  background-size:100% 100%;
}
.container{
  width: 1400px;
  margin: auto;
}
p{
  font-size: 24px;
  text-align: justify;
}
</style>
