<template>
  <div id="main">
    <div id="header">
      <Header active="help"></Header>
    </div>
    <div id="body">
        <div class="left-menu">
          <el-menu>
            <el-submenu index="1">
              <template slot="title">
                <span>Help</span>
              </template>
              <el-menu-item @click="helpGoTo('#introduction')">
                Introducation
              </el-menu-item>
              <el-menu-item @click="helpGoTo('#projects_list')">Browse project list
              </el-menu-item>
              <el-menu-item @click="helpGoTo('#register')">Register and log in
              </el-menu-item>
              <el-menu-item @click="helpGoTo('#details')">Browse project details
              </el-menu-item>
              <el-menu-item @click="helpGoTo('#projects_list')">upload your projects
              </el-menu-item>
            </el-submenu>
            <el-menu-item index="2" @click="showHelp=false">
              Contact US
            </el-menu-item>

          </el-menu>
        </div>
        <div class="content">
          <el-card class="contact-card">
            <div id="help" v-if="showHelp">
              <h1>Help</h1>
              <hr style="border:1px dashed #b6afd7;" />
              <div id="introduction">
                <h2>Introduction</h2>
                <p>
                  The DP-Library serves as a hub for the DP models for various systems generated by different groups, with focuses on the data generation protocol, the automatic testing scheme, as well as the transparency and reproducibility of related research projects. In this way, we hope to better serve the molecular simulation community in the age of machine learning.
                  Users can download the input data, output model and results of the model from the web and upload their own relevant data to the web.
                </p>
              </div>
              <div id="projects_list">
                <h2>Browse projects list</h2>
                <h3>
                  Home page
                </h3>
                <p>On the <el-link @click="router.push('/home')">home page</el-link>, users can browse the project page of corresponding elements by clicking on elements or mixtures as follows.</p>
                <h3>Click elements</h3>
                <p>Users can click elements in the <el-link @click="router.push('/home')">home page</el-link>, or input the elements list to browser the corresponding projects.</p>
                <img src="../assets/images/help-home1.jpg" class="img">
                <h3>
                  Projects list
                </h3>
                <p>Users can browse the basic information of the project from the
                  <el-link @click="router.push('/elements_list')">projects page</el-link>, and filter the <el-link @click="router.push('/elements_list')">projects page</el-link> by various conditions.</p>
                <img src="../assets/images/projects_list.png" class="img">

              </div>

              <div id="register">
                <h2>
                  <el-link @click="router.push('/elements_list')"><span class="h2-like">Register and log in</span></el-link>

                </h2>
                <p>For a better service, we request that the users should register their own accounts. Please fill
                  in your information carefully when registering. We will send an activation email to the
                  registered email address. You must click the activation email to complete the registration
                  process. After logging in, you can access the data in the library and upload your own
                  project.</p>
                <img src="../assets/images/help-register.png" class="img">
              </div>

              <div id="details">
                <h2>Browse projects details</h2>
                <h3>Entry projects
                  <el-link @click="router.push('/project_details')"><span style="font-size: 14px;">details page</span></el-link>
                </h3>
                <p>Users can click a project on the project page to enter the details page of the project.</p>
                <img src="../assets/images/help-details1.png" class="img">
                <h3>Download data</h3>
                <p>Users can click the download button to get raw data or model data. Please register and log in before downloading the input data, otherwise the data cannot be downloaded.
                </p>
                <h3>Browse test results</h3>
                <p>Users can see the result in the bellow part by choosing "Structure", "Task" and "Task type" of the result, and click the "Show results" button.
                </p>
                <img src="../assets/images/help-details2.png" class="img">

              </div>
              <div id="upload">
                <h2>Upload your projects</h2>
                <p>After logging in, you can create a project in the
                  <el-link @click="router.push('/append_project')">add project page</el-link> just as bellow：</p>
                <img src="../assets/images/help-upload1.png" class="img">

                <h3>Create projects</h3>
                <p>In <el-link @click="router.push('/append_project')">add project page</el-link>, You can fill in or select elements, authors, etc. to create a project.</p>
                <img src="../assets/images/help-add.png" class="img">
                <h3>Edit projects</h3>
                <p>After creating a project, you can edit the details of that project about raw data, model, references, test results and so on in <el-link @click="router.push('/user_projects')">My projects page</el-link>.
                  After editing, remember to click the submit button to update the information.</p>
                <img src="../assets/images/help-edit.png" class="img">
                <img src="../assets/images/help-edit2.png" class="img">
                <img src="../assets/images/help-edit3.png" class="img">
                <img src="../assets/images/help-edit4.png" class="img">
                <img src="../assets/images/help-edit5.png" class="img">
                <h3>Share your porject</h3>
                <p>When you confirm that the editing of porject is complete, you can click the "share button" to share the project on the projects list page for easy browsing.
                  Of course, you can also click "Don’t share" button again to hide the project.</p>




              </div>
            </div>
            <div id="contact" v-else>
              <h2>Contact US</h2>
              <hr style="border:1px dashed #b6afd7;" />
              <el-form :model="formData" :rules="rules" ref="form" label-width="1.00rem">
                <el-form-item label="Name" prop="name">
                  <el-input v-model="formData.name"></el-input>
                </el-form-item>
                <el-form-item label="Email" prop="email">
                  <el-input v-model="formData.email"></el-input>
                </el-form-item>
                <el-form-item label="Content" prop="data">
                  <el-input type="textarea" v-model="formData.data"></el-input>
                </el-form-item>
                <el-form-item label="Verification" prop="slide" class="verify-row">
                  <Verify  @success="alert('success')" explain="Slide to right" :show-button="false" @error="alert('error')" :type="3" :barSize="{width:'3.5rem',height:'0.28rem'}"></Verify>
                </el-form-item>
                <div style="text-align: center;">
                  <el-button round size="small" class="button-submit" @click="onSubmit">Submit</el-button>
                  <el-button round size="small" class="button-cancel" @click="reset">Cancel</el-button>
                </div>
              </el-form>
            </div>


          </el-card>




        </div>


    </div>

    <Footer class="footer"></Footer>

  </div>
</template>

<script>
  import Header from "../components/Header";
  import Footer from "../components/Footer";
  import Verify from 'vue2-verify';
    export default {
        name: "Help",
      data(){
        var validateEmail = (rule, value, callback) => {
          let regEmail = /^[A-Za-z0-9\u4e00-\u9fa5]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/
          if (regEmail.test(value)) {
            callback();
          } else {
            callback(new Error('Email Error'));
          }
        };
        var slidePass = (rule, value, callback) => {
          console.log('slide')
          if(value){
            callback();
          }else{

            this.$alert('Check slide verfication' ,'', {
              confirmButtonText: 'OK',
              showClose: false,
              iconClass: "el-icon-circle-close",
              center: true,
              customClass: 'success-box',
              callback: action => {
              }
            })
            callback(new Error('Slide Error'));
          }
        };
        return {
          showHelp: true,
          formData:{
            name: '',
            email: '',
            data: '',
            slide: false
          },
          rules:{
            name:[
              { required: true, message: 'Input your name', trigger: 'blur' },
              { min: 4, max: 36, message: 'Length between 4 and 36', trigger: 'blur' }
            ],
            email: [
              { required: true, validator: validateEmail, trigger: 'blur' }
            ],
            data:[
              { required: true, message: 'Input your opinion', trigger: 'blur' },
            ],
            slide: [
              { required: true, validator: slidePass, trigger: 'blur' }
            ],
          }
        }
      },
      methods:{
        goto(to){

          this.$router.push(to)
        },
        onSubmit(){
          this.$refs.form.validate((valid) => {
            if(valid){
              this.axios.post('/v1/user/insert_contact', {
                user_name: this.formData.name,
                email: this.formData.email,
                data: this.formData.data
              }).then(res=>{
                console.log(res.data)
                if(res.data.result >0){
                  this.$alert('Successfully upload' ,'', {
                    confirmButtonText: 'OK',
                    showClose: false,
                    iconClass: "el-icon-circle-check",
                    center: true,
                    customClass: 'success-box',
                    callback: action => {
                      // this.reload()
                      location.reload();
                    }
                  })
                }else{
                  console.log(res.data.result)
                  // this.showErr = true
                  this.$alert('Upload Failure' ,'', {
                    confirmButtonText: 'OK',
                    showClose: false,
                    iconClass: "el-icon-circle-close",
                    center: true,
                    customClass: 'success-box',
                    callback: action => {
                      // this.reload()
                      location.reload();
                    }

                  })
                }

              }).catch(err=>{
                console.log(err)
              })
            }else{
              console.log('error submit')
              return false
            }
          })
        },
        reset(){
          this.$refs['form'].resetFields();
        },
        alert(text) {
          console.log(text)
          if(text == "success"){
            this.formData.slide = true
          }
        },
        helpGoTo(id){
          this.showHelp=true;
          location.href=id;
        }
      },
      components:{
          Header,
        Footer,
        Verify
      }
    }
</script>

<style scoped lang="scss">
  #main{
    #header{
      width: 100%;
      height: 100px;
      background: url("../assets/images/详情页头图.png");
      background-size:100% 100%;
      position: fixed;
      top: 0;
      z-index: 100;
    }
    .footer{
      position: relative;
      z-index: 100;
    }
    #body{
      font-family: "Microsoft Ya Hei";
      width: 1400px;
      margin: 100px auto 0;
      min-height: 850px;
      padding:0 20px;
      position: relative;


      .left-menu{
        width:400px;
        position:fixed;
        left:260px;
        top: 110px;
        background-color: rgba(255,255,255,0.5);
        height: 640px;
        box-shadow: 0px 0px 5px #dadbed;
        color: #fff;


        >>> .el-menu{
          background-color: transparent;
          border: 0;
        }

      }

      .link{
        text-decoration: none;
      }

      .content{
        width:920px;
        margin-left: 400px;
        padding-top: 10px;
        padding-left: 10px;

        .contact-card{
          /*margin-top: 10px;*/
        }

        >>> .el-link--inner{
          color: #409EFF;
          font-size: 12PX;
        }

        h1 {
          font-size: 42px;
        }
        h2{
          font-size: 30px;
        }
        .h2-like{
          font-size: 30px;
        }
        p{
          text-align: justify;
        }
      }


    }
    .img{
      width: 800px;
    }

    .button-submit{
      background-color: #33327e;
      color: #fff;
      border: 0;
    }

    .button-cancel{
      background-color: #e1e1e1;
      color: #fff;
      border: 0;
    }
    >>> .el-textarea__inner{
      resize: none;
    }
  }

</style>
