<template>
  <div id="home">
    <div id="title">
      <Header active="home"></Header>
    </div>
    <div id="header-text">
      <div class="text-panel">
        <el-carousel id="carousel" :interval="2000" trigger="click"  height="3rem">

          <el-carousel-item>
            <el-row>
              <el-col :span="20">
                <h2>Overview</h2>
                <p>
                  Machine learning-based methods are changing the way people use to develop interatomic
                  potential energy surface (PES) models. In this context, the two aspects, model and data, are
                  equally important. One needs a good PES model to fit ab initio data within satisfactory accuracy;
                  One also needs a good set of data to produce a reliable PES model by training. This new demand
                  has been the impetus behind our persistent efforts on the development of the
                  <a href="https://github.com/deepmodeling/deepmd-kit">Deep Potential (DP)</a>
                  model and the
                  <a href="https://github.com/deepmodeling/dpgen">Deep Potential Generator (DP-GEN)</a>
                  scheme.
                  The DP-Library serves as a hub for the DP models for various systems generated by different
                  groups, with focuses on the data generation protocol, the automatic testing scheme, as well as
                  the transparency and reproducibility of related research projects. In this way, we hope to better
                  serve the molecular simulation community in the age of machine learning.
                </p>
              </el-col>
              <!--          <el-col :span="8">-->
              <!--            <img class="text-img" src="../assets/images/首页插图.png">-->
              <!--          </el-col>-->
            </el-row>
          </el-carousel-item>
          <el-carousel-item>
            <el-row>
              <el-col :span="8">
                <img class="text-img" src="../assets/images/首页插图.png">
              </el-col>
            </el-row>
          </el-carousel-item>
        </el-carousel>



      </div>
    </div>

    <div id="main">
      <div id="element-panel">
        <div id="search-form">
          <div style="">
            <el-input v-model="search" placeholder="Na-O" class="search-input" @input="searchChange"></el-input>
            <el-icon class="el-icon-close search-close" @click.native="clearSearch()"></el-icon>
            <el-button @click="submitSearch()" class="search-button">Search</el-button>
          </div>

        </div>
        <div class="table-div">
          <table id="table" class="element-table">
            <tbody>
            <tr>
              <td class="element non-metal">
                <div id="H" class="symbol_element"  :style="{'cursor':elements['H']?'pointer':'not-allowed'}">
                  <ElementCell :content="elements['H']" :haveProjects="elements['H']" index="1" title="H" @click.native="elementClick('H')" ></ElementCell>
                  <!--              <el-tooltip :content="elements['H']" v-if="elements['H']">

                                  <el-link :href="haveProjects('H')?'/elements_list?elements=H':''">1<br>H</el-link>
                                </el-tooltip>
                                <div v-else>
                                  1<br>H
                                </div>-->
                </div>
              </td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element noble"><div id="He" class="symbol_element" :style="{'cursor':elements['He']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['He']" :haveProjects="elements['He']" index="2" title="He"  @click.native="elementClick('He')" ></ElementCell>
              </div></td>
            </tr>
            <tr>
              <td class="element alkali"><div id="Li" class="symbol_element" :style="{'cursor':elements['Li']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Li']" :haveProjects="elements['Li']" index="3" title="Li" @click.native="elementClick('Li')" ></ElementCell>
              </div></td>
              <td class="element alkaline"><div id="Be" class="symbol_element" :style="{'cursor':elements['Be']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Be']" :haveProjects="elements['Be']" index="4" title="Be" @click.native="elementClick('Be')"></ElementCell>
              </div></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element metalloid" ><div id="B" class="symbol_element" :style="{'cursor':elements['B']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['B']" :haveProjects="elements['B']" index="5" title="B" @click.native="elementClick('B')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="C" class="symbol_element" :style="{'cursor':elements['C']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['C']" :haveProjects="elements['C']" index="6" title="C" @click.native="elementClick('C')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="N" class="symbol_element" :style="{'cursor':elements['N']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['N']" :haveProjects="elements['N']" index="7" title="N" @click.native="elementClick('N')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="O" class="symbol_element" :style="{'cursor':elements['O']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['O']" :haveProjects="elements['O']" index="8" title="O" @click.native="elementClick('O')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="F" class="symbol_element" :style="{'cursor':elements['F']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['F']" :haveProjects="elements['F']" index="9" title="F" @click.native="elementClick('F')"></ElementCell>
              </div></td>
              <td class="element noble"><div id="Ne" class="symbol_element" :style="{'cursor':elements['Ne']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ne']" :haveProjects="elements['Ne']" index="10" title="Ne" @click.native="elementClick('Ne')"></ElementCell>
              </div></td>
            </tr>
            <tr>
              <td class="element alkali"><div id="Na" class="symbol_element" :style="{'cursor':elements['Na']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Na']" :haveProjects="elements['Na']" index="11" title="Na" @click.native="elementClick('Na')"></ElementCell>
              </div></td>
              <td class="element alkaline"><div id="Mg" class="symbol_element" :style="{'cursor':elements['Mg']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Mg']" :haveProjects="elements['Mg']" index="12" title="Mg" @click.native="elementClick('Mg')"></ElementCell>
              </div></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element empty"><br></td>
              <td class="element post-transition"><div id="Al" class="symbol_element" :style="{'cursor':elements['Al']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Al']" :haveProjects="elements['Al']" index="13" title="Al" @click.native="elementClick('Al')"></ElementCell>
              </div></td>
              <td class="element metalloid"><div id="Si" class="symbol_element" :style="{'cursor':elements['Si']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Si']" :haveProjects="elements['Si']" index="14" title="Si" @click.native="elementClick('Si')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="P" class="symbol_element" :style="{'cursor':elements['P']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['P']" :haveProjects="elements['P']" index="15" title="P" @click.native="elementClick('P')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="S" class="symbol_element" :style="{'cursor':elements['S']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['S']" :haveProjects="elements['S']" index="16" title="S" @click.native="elementClick('S')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="Cl" class="symbol_element" :style="{'cursor':elements['Cl']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Cl']" :haveProjects="elements['Cl']" index="17" title="Cl" @click.native="elementClick('Cl')"></ElementCell>
              </div></td>
              <td class="element noble"><div id="Ar" class="symbol_element" :style="{'cursor':elements['Ar']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ar']" :haveProjects="elements['Ar']" index="18" title="Ar" @click.native="elementClick('Ar')"></ElementCell>
              </div></td>
            </tr>
            <tr>
              <td class="element alkali"><div id="K" class="symbol_element" :style="{'cursor':elements['K']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['K']" :haveProjects="elements['K']" index="19" title="K" @click.native="elementClick('K')"></ElementCell>
              </div></td>
              <td class="element alkaline"><div id="Ca" class="symbol_element" :style="{'cursor':elements['Ca']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ca']" :haveProjects="elements['Ca']" index="20" title="Ca" @click.native="elementClick('Ca')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Sc" class="symbol_element" :style="{'cursor':elements['Sc']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Sc']" :haveProjects="elements['Sc']" index="21" title="Sc"  @click.native="elementClick('Sc')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Ti" class="symbol_element" :style="{'cursor':elements['Ti']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ti']" :haveProjects="elements['Ti']" index="22" title="Ti"  @click.native="elementClick('Ti')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="V" class="symbol_element" :style="{'cursor':elements['V']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['V']" :haveProjects="elements['V']" index="23" title="V"  @click.native="elementClick('V')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Cr" class="symbol_element" :style="{'cursor':elements['Cr']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Cr']" :haveProjects="elements['Cr']" index="24" title="Cr"  @click.native="elementClick('Cr')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Mn" class="symbol_element" :style="{'cursor':elements['Mn']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Mn']" :haveProjects="elements['Mn']" index="25" title="Mn"  @click.native="elementClick('Mn')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Fe" class="symbol_element" :style="{'cursor':elements['Fe']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Fe']" :haveProjects="elements['Fe']" index="26" title="Fe"  @click.native="elementClick('Fe')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Co" class="symbol_element" :style="{'cursor':elements['Co']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Co']" :haveProjects="elements['Co']" index="27" title="Co"  @click.native="elementClick('Co')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Ni" class="symbol_element" :style="{'cursor':elements['Ni']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ni']" :haveProjects="elements['Ni']" index="28" title="Ni"  @click.native="elementClick('Ni')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Cu" class="symbol_element" :style="{'cursor':elements['Cu']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Cu']" :haveProjects="elements['Cu']" index="29" title="Cu"  @click.native="elementClick('Cu')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Zn" class="symbol_element" :style="{'cursor':elements['Zn']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Zn']" :haveProjects="elements['Zn']" index="30" title="Zn"  @click.native="elementClick('Zn')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Ga" class="symbol_element" :style="{'cursor':elements['Ga']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ga']" :haveProjects="elements['Ga']" index="31" title="Ga"  @click.native="elementClick('Ga')"></ElementCell>
              </div></td>
              <td class="element metalloid"><div id="Ge" class="symbol_element" :style="{'cursor':elements['Ge']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ge']" :haveProjects="elements['Ge']" index="32" title="Ge"  @click.native="elementClick('Ge')"></ElementCell>
              </div></td>
              <td class="element metalloid"><div id="As" class="symbol_element" :style="{'cursor':elements['As']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['As']" :haveProjects="elements['As']" index="33" title="As"  @click.native="elementClick('As')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="Se" class="symbol_element" :style="{'cursor':elements['Se']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Se']" :haveProjects="elements['Se']" index="34" title="Se"  @click.native="elementClick('Se')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="Br" class="symbol_element" :style="{'cursor':elements['Br']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Br']" :haveProjects="elements['Br']" index="35" title="Br"  @click.native="elementClick('Br')"></ElementCell>
              </div></td>
              <td class="element noble"><div id="Kr" class="symbol_element" :style="{'cursor':elements['Kr']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Kr']" :haveProjects="elements['Kr']" index="36" title="Kr"  @click.native="elementClick('Kr')"></ElementCell>
              </div></td>
            </tr>
            <tr>
              <td class="element alkali"><div id="Rb" class="symbol_element" :style="{'cursor':elements['Rb']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Rb']" :haveProjects="elements['Rb']" index="37" title="Rb"  @click.native="elementClick('Rb')"></ElementCell>
              </div></td>
              <td class="element alkaline"><div id="Sr" class="symbol_element" :style="{'cursor':elements['Sr']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Sr']" :haveProjects="elements['Sr']" index="38" title="Sr"  @click.native="elementClick('Sr')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Y" class="symbol_element" :style="{'cursor':elements['Y']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Y']" :haveProjects="elements['Y']" index="39" title="Y"  @click.native="elementClick('Y')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Zr" class="symbol_element" :style="{'cursor':elements['Zr']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Zr']" :haveProjects="elements['Zr']" index="40" title="Zr"  @click.native="elementClick('Zr')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Nb" class="symbol_element" :style="{'cursor':elements['Nb']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Nb']" :haveProjects="elements['Nb']" index="41" title="Nb"  @click.native="elementClick('Nb')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Mo" class="symbol_element" :style="{'cursor':elements['Mo']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Mo']" :haveProjects="elements['Mo']" index="42" title="Mo"  @click.native="elementClick('Mo')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Tc" class="symbol_element" :style="{'cursor':elements['Tc']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Tc']" :haveProjects="elements['Tc']" index="43" title="Tc"  @click.native="elementClick('Tc')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Ru" class="symbol_element" :style="{'cursor':elements['Ru']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ru']" :haveProjects="elements['Ru']" index="44" title="Ru"  @click.native="elementClick('Ru')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Rh" class="symbol_element" :style="{'cursor':elements['Rh']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Rh']" :haveProjects="elements['Rh']" index="45" title="Rh"  @click.native="elementClick('Rh')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Pd" class="symbol_element" :style="{'cursor':elements['Pd']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Pd']" :haveProjects="elements['Pd']" index="46" title="Pd"  @click.native="elementClick('Pd')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Ag" class="symbol_element" :style="{'cursor':elements['Ag']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ag']" :haveProjects="elements['Ag']" index="47" title="Ag"  @click.native="elementClick('Ag')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Cd" class="symbol_element" :style="{'cursor':elements['Cd']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Cd']" :haveProjects="elements['Cd']" index="48" title="Cd"  @click.native="elementClick('Cd')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="In" class="symbol_element" :style="{'cursor':elements['In']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['In']" :haveProjects="elements['In']" index="49" title="In"  @click.native="elementClick('In')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Sn" class="symbol_element" :style="{'cursor':elements['Sn']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Sn']" :haveProjects="elements['Sn']" index="50" title="Sn"  @click.native="elementClick('Sn')"></ElementCell>
              </div></td>
              <td class="element metalloid"><div id="Sb" class="symbol_element" :style="{'cursor':elements['Sb']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Sb']" :haveProjects="elements['Sb']" index="51" title="Sb"  @click.native="elementClick('Sb')"></ElementCell>
              </div></td>
              <td class="element metalloid"><div id="Te" class="symbol_element" :style="{'cursor':elements['Te']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Te']" :haveProjects="elements['Te']" index="52" title="Te"  @click.native="elementClick('Te')"></ElementCell>
              </div></td>
              <td class="element non-metal"><div id="I" class="symbol_element" :style="{'cursor':elements['I']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['I']" :haveProjects="elements['I']" index="53" title="I"  @click.native="elementClick('I')"></ElementCell>
              </div></td>
              <td class="element noble"><div id="Xe" class="symbol_element" :style="{'cursor':elements['Xe']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Xe']" :haveProjects="elements['Xe']" index="54" title="Xe"  @click.native="elementClick('Xe')"></ElementCell>
              </div></td>
            </tr>
            <tr>
              <td class="element alkali"><div id="Cs" class="symbol_element" :style="{'cursor':elements['Cs']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Cs']" :haveProjects="elements['Cs']" index="55" title="Cs"  @click.native="elementClick('Cs')"></ElementCell>
              </div></td>
              <td class="element alkaline"><div id="Ba" class="symbol_element" :style="{'cursor':elements['Ba']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ba']" :haveProjects="elements['Ba']" index="56" title="Ba"  @click.native="elementClick('Ba')"></ElementCell>
              </div></td>
              <td class="element star">*<br></td>
              <td class="element transition"><div id="Hf" class="symbol_element" :style="{'cursor':elements['Hf']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Hf']" :haveProjects="elements['Hf']" index="72" title="Hf"  @click.native="elementClick('Nf')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Ta" class="symbol_element" :style="{'cursor':elements['Ta']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ta']" :haveProjects="elements['Ta']" index="73" title="Ta"  @click.native="elementClick('Ta')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="W" class="symbol_element" :style="{'cursor':elements['W']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['W']" :haveProjects="elements['W']" index="74" title="W"  @click.native="elementClick('W')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Re" class="symbol_element" :style="{'cursor':elements['Re']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Re']" :haveProjects="elements['Re']" index="75" title="Re"  @click.native="elementClick('Re')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Os" class="symbol_element" :style="{'cursor':elements['Os']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Os']" :haveProjects="elements['Os']" index="76" title="Os"  @click.native="elementClick('Os')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Ir" class="symbol_element" :style="{'cursor':elements['Tr']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ir']" :haveProjects="elements['Ir']" index="77" title="Ir"  @click.native="elementClick('ir')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Pt" class="symbol_element" :style="{'cursor':elements['Pt']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Pt']" :haveProjects="elements['Pt']" index="78" title="Pt"  @click.native="elementClick('Pt')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Au" class="symbol_element" :style="{'cursor':elements['Au']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Au']" :haveProjects="elements['Au']" index="79" title="Au"  @click.native="elementClick('Au')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Hg" class="symbol_element" :style="{'cursor':elements['Hg']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Hg']" :haveProjects="elements['Hg']" index="80" title="Hg" @click.native="elementClick('Hg')" ></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Tl" class="symbol_element" :style="{'cursor':elements['Tl']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Tl']" :haveProjects="elements['Tl']" index="81" title="Tl"  @click.native="elementClick('Tl')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Pb" class="symbol_element" :style="{'cursor':elements['Pb']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Pb']" :haveProjects="elements['Pb']" index="82" title="Pb"  @click.native="elementClick('Pb')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Bi" class="symbol_element" :style="{'cursor':elements['Bi']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Bi']" :haveProjects="elements['Bi']" index="83" title="Bi"  @click.native="elementClick('Bi')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Po" class="symbol_element" :style="{'cursor':elements['Po']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Po']" :haveProjects="elements['Po']" index="84" title="Po"  @click.native="elementClick('Po')"></ElementCell>
              </div></td>
              <td class="element metalloid"><div id="At" class="symbol_element" :style="{'cursor':elements['At']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['At']" :haveProjects="elements['At']" index="85" title="At"  @click.native="elementClick('At')"></ElementCell>
              </div></td>
              <td class="element noble"><div id="Rn" class="symbol_element" :style="{'cursor':elements['Rn']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Rn']" :haveProjects="elements['Rn']" index="86" title="Rn"  @click.native="elementClick('Rn')"></ElementCell>
              </div></td>
            </tr>
            <tr>
              <td class="element alkali"><div id="Fr" class="symbol_element" :style="{'cursor':elements['Fr']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Fr']" :haveProjects="elements['Fr']" index="87" title="Fr"  @click.native="elementClick('Fr')"></ElementCell>
              </div></td>
              <td class="element alkaline"><div id="Ra" class="symbol_element" :style="{'cursor':elements['Ra']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ra']" :haveProjects="elements['Ra']" index="88" title="Ra"  @click.native="elementClick('Ra')"></ElementCell>
              </div></td>
              <td class="element star">**<br></td>
              <td class="element transition"><div id="Rf" class="symbol_element" :style="{'cursor':elements['Rf']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Rf']" :haveProjects="elements['Rf']" index="104" title="Rf"  @click.native="elementClick('Rf')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Db" class="symbol_element" :style="{'cursor':elements['Db']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Db']" :haveProjects="elements['Db']" index="105" title="Db"  @click.native="elementClick('Db')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Sg" class="symbol_element" :style="{'cursor':elements['Sg']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Sg']" :haveProjects="elements['Sg']" index="106" title="Sg"  @click.native="elementClick('Sg')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Bh" class="symbol_element" :style="{'cursor':elements['Bh']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Bh']" :haveProjects="elements['Bh']" index="107" title="Bh"  @click.native="elementClick('Bh')"></ElementCell>
              </div></td>
              <td class="element transition"><div id="Hs" class="symbol_element" :style="{'cursor':elements['Hs']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Hs']" :haveProjects="elements['Hs']" index="108" title="Hs"  @click.native="elementClick('Hs')"></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Mt" class="symbol_element" :style="{'cursor':elements['Mt']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Mt']" :haveProjects="elements['Mt']" index="109" title="Mt"  @click.native="elementClick('Mt')"></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Ds" class="symbol_element" :style="{'cursor':elements['Ds']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ds']" :haveProjects="elements['Ds']" index="110" title="Ds"  @click.native="elementClick('Ds')"></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Rg" class="symbol_element" :style="{'cursor':elements['Rg']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Rg']" :haveProjects="elements['Rg']" index="111" title="Rg"  @click.native="elementClick('Rg')"></ElementCell>
              </div></td>
              <td class="element post-transition"><div id="Cn" class="symbol_element" :style="{'cursor':elements['Cn']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Cn']" :haveProjects="elements['Cn']" index="112" title="Cn"  @click.native="elementClick('Cn')"></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Nh" class="symbol_element" :style="{'cursor':elements['Nh']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Nh']" :haveProjects="elements['Nh']" index="113" title="Nh"  @click.native="elementClick('Nh')"></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Fl" class="symbol_element" :style="{'cursor':elements['Fl']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Fl']" :haveProjects="elements['Fl']" index="114" title="Fl"  @click.native="elementClick('Fl')"></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Mc" class="symbol_element" :style="{'cursor':elements['Mc']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Mc']" :haveProjects="elements['Mc']" index="115" title="Mc" @click.native="elementClick('Mc')" ></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Lv" class="symbol_element" :style="{'cursor':elements['Lv']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Lv']" :haveProjects="elements['Lv']" index="116" title="Lv" @click.native="elementClick('Lv')" ></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Ts" class="symbol_element" :style="{'cursor':elements['Ts']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ts']" :haveProjects="elements['Ts']" index="117" title="Ts" @click.native="elementClick('Ts')" ></ElementCell>
              </div></td>
              <td class="element unclassified"><div id="Og" class="symbol_element" :style="{'cursor':elements['Og']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Og']" :haveProjects="elements['Og']" index="118" title="Og" @click.native="elementClick('Og')" ></ElementCell>
              </div></td>
            </tr>
            <tr>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
              <td class=" separator"><br></td>
            </tr>
            <tr>
              <td class="element empty"><br></td>
              <td class="element star">*</td>
              <td class="element lanthanide"><div id="La" class="symbol_element" :style="{'cursor':elements['La']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['La']" :haveProjects="elements['La']" index="57" title="La" @click.native="elementClick('La')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Ce" class="symbol_element" :style="{'cursor':elements['Ce']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ce']" :haveProjects="elements['Ce']" index="58" title="Ce" @click.native="elementClick('Ce')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Pr" class="symbol_element" :style="{'cursor':elements['Pr']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Pr']" :haveProjects="elements['Pr']" index="59" title="Pr" @click.native="elementClick('Pr')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Nd" class="symbol_element" :style="{'cursor':elements['Nd']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Nd']" :haveProjects="elements['Nd']" index="60" title="Nd" @click.native="elementClick('Nd')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Pm" class="symbol_element" :style="{'cursor':elements['Pm']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Pm']" :haveProjects="elements['Pm']" index="61" title="Pm" @click.native="elementClick('Pm')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Sm" class="symbol_element" :style="{'cursor':elements['Sm']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Sm']" :haveProjects="elements['Sm']" index="62" title="Sm" @click.native="elementClick('Sm')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Eu" class="symbol_element" :style="{'cursor':elements['Eu']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Eu']" :haveProjects="elements['Eu']" index="63" title="Eu" @click.native="elementClick('Eu')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Gd" class="symbol_element" :style="{'cursor':elements['Gd']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Gd']" :haveProjects="elements['Gd']" index="64" title="Gd" @click.native="elementClick('Gd')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Tb" class="symbol_element" :style="{'cursor':elements['Th']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Tb']" :haveProjects="elements['Tb']" index="65" title="Tb" @click.native="elementClick('Tb')"></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Dy" class="symbol_element" :style="{'cursor':elements['Dy']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Dy']" :haveProjects="elements['Dy']" index="66" title="Dy" @click.native="elementClick('Dy')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Ho" class="symbol_element" :style="{'cursor':elements['Ho']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ho']" :haveProjects="elements['Ho']" index="67" title="Ho" @click.native="elementClick('Ho')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Er" class="symbol_element" :style="{'cursor':elements['Er']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Er']" :haveProjects="elements['Er']" index="68" title="Er" @click.native="elementClick('Er')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Tm" class="symbol_element" :style="{'cursor':elements['Tm']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Tm']" :haveProjects="elements['Tm']" index="69" title="Tm" @click.native="elementClick('Tm')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Yb" class="symbol_element" :style="{'cursor':elements['Yb']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Yb']" :haveProjects="elements['Yb']" index="70" title="Yb" @click.native="elementClick('Yb')" ></ElementCell>
              </div></td>
              <td class="element lanthanide"><div id="Lu" class="symbol_element" :style="{'cursor':elements['Lu']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Lu']" :haveProjects="elements['Lu']" index="71" title="Lu"@click.native="elementClick('Lu')"  ></ElementCell>
              </div></td>
              <td class="element empty"><br></td>
            </tr>
            <tr>
              <td class="element empty"><br></td>
              <td class="element star">**<br></td>
              <td class="element actinide"><div id="Ac" class="symbol_element" :style="{'cursor':elements['Ac']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Ac']" :haveProjects="elements['Ac']" index="89" title="Ac" @click.native="elementClick('Ac')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Th" class="symbol_element" :style="{'cursor':elements['Th']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Th']" :haveProjects="elements['Th']" index="90" title="Th" @click.native="elementClick('Th')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Pa" class="symbol_element" :style="{'cursor':elements['Pa']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Pa']" :haveProjects="elements['Pa']" index="91" title="Pa" @click.native="elementClick('Pa')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="U" class="symbol_element" :style="{'cursor':elements['U']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['U']" :haveProjects="elements['U']" index="92" title="U" @click.native="elementClick('U')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Np" class="symbol_element" :style="{'cursor':elements['Np']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Np']" :haveProjects="elements['Np']" index="93" title="Np" @click.native="elementClick('Np')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Pu" class="symbol_element" :style="{'cursor':elements['Pu']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Pu']" :haveProjects="elements['Pu']" index="94" title="Pu" @click.native="elementClick('Pu')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Am" class="symbol_element" :style="{'cursor':elements['Am']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Am']" :haveProjects="elements['Am']" index="95" title="Am" @click.native="elementClick('Am')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Cm" class="symbol_element" :style="{'cursor':elements['Cm']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Cm']" :haveProjects="elements['Cm']" index="96" title="Cm" @click.native="elementClick('Cm')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Bk" class="symbol_element" :style="{'cursor':elements['Bk']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Bk']" :haveProjects="elements['Bk']" index="97" title="Bk" @click.native="elementClick('Bk')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Cf" class="symbol_element" :style="{'cursor':elements['Cf']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Cf']" :haveProjects="elements['Cf']" index="98" title="Cf" @click.native="elementClick('Cf')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Es" class="symbol_element" :style="{'cursor':elements['Es']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Es']" :haveProjects="elements['Es']" index="99" title="Es" @click.native="elementClick('Es')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Fm" class="symbol_element" :style="{'cursor':elements['Fm']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Fm']" :haveProjects="elements['Fm']" index="100" title="Fm" @click.native="elementClick('Fm')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Md" class="symbol_element" :style="{'cursor':elements['Md']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Md']" :haveProjects="elements['Md']" index="101" title="Md" @click.native="elementClick('Md')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="No" class="symbol_element" :style="{'cursor':elements['No']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['No']" :haveProjects="elements['No']" index="102" title="No" @click.native="elementClick('No')" ></ElementCell>
              </div></td>
              <td class="element actinide"><div id="Lr" class="symbol_element" :style="{'cursor':elements['Lr']?'pointer':'not-allowed'}">
                <ElementCell :content="elements['Lr']" :haveProjects="elements['Lr']" index="103" title="Lr" @click.native="elementClick('Lr')" ></ElementCell>
              </div></td>
              <td class="element empty"><br>
              </td>
            </tr>
            </tbody>
          </table>
        </div>

      </div>

      <div id="components-list" class="components-list">
        <div class="center-panel">
          <h2>Alloys, Compounds, and Mixtures</h2>
          <p>
            Listed alphabetically by the elemental system or the compound(s) the potentials were designed for.
            For elemental systems, the components are listed alphabetically.
          </p>
          <el-row>
            <el-col :span="4" v-for="(value,key) in mixturesShow"  :id="key" :key="key" class="mixture-item">

              <el-tooltip :content="'Number of projects: '+value">
                <el-button round class="round-button" @click="$router.push({path:'/elements_list/',query:{elements: key}})">
                  {{ key }}
                </el-button>
              </el-tooltip>

            </el-col>
          </el-row>
          <p>
            Fictional potentials.  These are included for reproducibility but not
            meant to accurately reflect real materials.
          </p>
          <p>
            <strong class="text-warning">NOTE:</strong> multi-component element system potentials may not be applicable to the full
            composition range as they are often designed for specific compounds and/or composition ranges. See
            potential descriptions for more usage information.
          </p>
        </div>


      </div>
    </div>
    <Footer></Footer>
  </div>


</template>

<script>
  import Header from "../components/Header"
  import ElementCell from "../components/ElementCell";
  import Footer from "../components/Footer"
  import Vue from 'vue'
  export default {
        name: "Home",
        data(){
            return {
              elements: {},
              mixtures: {},
              mixturesShow:{},
              search: '',
              elementList: [],
              list1: ['B','C','N','O','F','Ne'],
              list2: ['Al','Si','P','S','Cl','Ar'],
              list3: ['K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr'],
              list4: ['Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe'],
              list5: ['Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn'],
              list6: ['Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'],
              list7: ['La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu'],
              list8: ['Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr']
            }
        },
        created(){
          this.axios.get('/v1/projects/get_elements_data').then(res=>{
            for(let element in res.data.result_element_data){
              this.elements[element] = res.data.result_element_data[element]
            }
            console.log(this.elements)
            this.mixtures = res.data.result_alloy
            this.mixturesShow = this.mixtures

            // this.mixtures = elements
          }).catch(err=>{
            console.log(err)
          })
        },
        components: {
          Header,
          Footer,
          ElementCell
        },
      methods:{
        /*haveProjects(element){
          for(let key in this.elements){
            if(key == element){
              // delete this.mixtures[key]
              return true
            }
          }
          return false
        },*/
        elementClick(value){
          console.log(value)
          console.log(this.elementList)
          let index = this.elementList.indexOf(value)
          if(index < 0){
            this.elementList.push(value)
          }else{
            this.elementList.splice(index,1)
          }
          this.mixturesShow = JSON.parse(JSON.stringify(this.mixtures))
          for(let key in this.mixturesShow){
            for(let element of this.elementList){
              if(key.indexOf(element)<0){
                delete this.mixturesShow[key]
              }
            }
          }

          this.listToString()


        },
        searchChange(){
          this.elementList = []
          let searchList = this.search.split('-')
          for(let item of searchList){
            if(item){
              this.elementList.push(item)
            }
          }
          console.log(this.elementList)
          this.mixturesShow = JSON.parse(JSON.stringify(this.mixtures))

          for(let key in this.mixturesShow){
            let keySplit = key.split('-')
            for(let element of this.elementList){
              if(keySplit.indexOf(element)<0){
                this.$delete(this.mixturesShow,key)
              }
            }
          }
          console.log(this.mixturesShow)
        },
        listToString(){
          this.search = ''
          for(let item of this.elementList){
            this.search += item + '-'
          }
        },
        clearSearch(){
          console.log(this.search)
          this.elementList = []
          this.mixturesShow = this.mixtures
          this.search = ""
        },
        submitSearch(){

          this.$router.push({path: '/elements_list', query:{
              elements: this.search
            }
          })
        }
      }
    }
</script>

<style>
  .el-input{
    font-size: 22px!important;
  }
</style>

<style scoped>

  p,h2,h3{
    font-family: "Microsoft Ya Hei";
  }
  h2  {
    font-size: 48px;
  }
  #title {
    width: 100%;
    background-image: url("../assets/images/首页导航背景.png");
    height:100px;
    background-size:100% 100%;
  }
  .mixture-item{
    margin: 15px 0;
  }

  .mixture-item >>> .el-button{
    font-weight: 700;
  }

  #header-text{
    /*margin-top: 100px;*/
    background-image: url("../assets/images/首页头部内容背景.png");
    height: 600px;
    background-size:100% 100%;
  }

  .components-list {
    background: url("../assets/images/首页下半部分背景图.png");
    background-size:100% 100%;
    padding: 60px 0;
  }
  .center-panel{
    width: 1400px;
    margin: 0 auto;
  }

  .components-list h2 {
    font: 40px/56px "Microsoft Ya Hei" ;
    color: #fafcff;
  }
  .components-list >>> .el-button {
    font-size: 22px;
    height: 50px;
  }

  .components-list p {
    color: #fff;
    font-size: 22px;
    line-height: 28px;
    text-align: justify;
  }
  .text-panel p{
    color: #ffffff;
    font-size: 22px;
    line-height: 30px;
    font-family: "Microsoft Ya Hei";
    word-wrap:break-word;
  }

  .text-panel h2{
    color: #ffffff;
    font-size: 48px;
    font-family: "Microsoft Ya Hei";
  }
  .text-panel a:link{
    color: #ff9030;
  }


  .text-panel a:visited{
    color: #d6a01d;
  }

  .text-panel >>> .el-link{
    font-size: 22px;
  }

  /*search */
  #search-form{
    text-align: center;
  }
  .search-input{
    width: 900px;
    vertical-align: middle;
  }
  .search-close{
    margin: 12px  0 0 -50px;
    z-index: 200;
    position: absolute;
    font-size: 22px;
  }

  #search-form >>> .el-input__inner{
    height: 50px;
    line-height: 50px;
  }

  #search-form >>>.el-input__inner:focus{
    border-color: #33327e;
  }

  #search-form >>>.el-button{
    line-height: 24px;
    height: 50px;
    vertical-align: middle;
  }

  #search-form >>> .el-button:hover{
    color: #fff;
    /* border-color: #b3d9d9; */
    background-color: #33327e;
  }

  /*table*/
  table {
    width: 1400px;
    margin: 21px auto;
    border-spacing: 10px;
    /*border-collapse: collapse;*/
  }
  .element {
    width: 60px;
    height: 60px;
    text-align: center;
    border-radius: 10px;
  }
  .separator {
    width: 5%;
    height: 28px;
  }
  .element.alkali {
    background-color: #f96989;
  }
  .element.alkaline {
    background-color: #ff9030;
  }
  .element.noble {
    background-color: #13beff;
  }
  .element.transition {
    background-color: #f3cf53;
  }
  .element.post-transition {
    background-color: #d1d1d1;
  }
  .element.metalloid {
    background-color: #aab8ca;
  }
  .element.non-metal {
    background-color: #84d6c0;
  }
  .element.lanthanide {
    background-color: #d473d2;
  }
  .element.actinide {
    background-color: #c37ae6;
  }
  .element.unclassified {
    background-color: #acb8c8;
  }
  .symbol{
    font-weight:bold;
    cursor:pointer;
    text-decoration: underline;
  }
  .element-table td {
    font-size: 22px;
    font-weight: 400;
    line-height: 24px;
  }
  .text-panel{
    width:1400px;
    margin: 0 auto;
  }
  .round-button{
    background-color: #61629b;
    border: 0;
    color: #fff;
  }
  #element-panel{
    background-color: #ecf2fc;
    padding: 40px 0;
  }
  .table-div{
    padding-top: 21px;
  }
  .text-img{
    height: 430px;
    margin-top: 20px;
  }

  #carousel >>> .el-icon-arrow-right{
    font-size: 40px;
    font-weight: 700;
  }
  #carousel >>> .el-icon-arrow-left{
    font-size: 40px;
    font-weight: 700;
  }
</style>
